### ISSUE TITLE
getting syntax error attempting to install monkeypatch.

### ISSUE THREAD

**Issue by mehbebe** [iki/monkeypatch#3]
Hello, I am using oobabooga webui, and one of the scripts in that webui requires monkeypatch to be installed.
I attempted to install monkeypatch using "pip install monkeypatch", and got the following error returned:

```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\username\AppData\Local\Temp\pip-install-6dbxphts\monkeypatch_f06937c6f11a4bcbb510558679cc65e8\setup.py", line 99
          except ImportError, e:
                 ^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]
```
      
I don't really understand why I am getting this error, as I can see other people are successfully installing it without any issues.
Could it possibly be that this version of monkeypatch isn't compatible with my version of python?
my version of python:
`3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]`

**Comment by TheNitzel** [comment]
Exact same situation here too.  Did you have any luck?

**Comment by mejerrytech** [comment]
To fix this issue, you should modify this line to use parentheses around the exception types:
Setup.py 

except (ImportError, e):

**Comment by baljeetn** [comment]
To fix this issue, you should modify this line to use parentheses around the exception types:
Setup.py

except (ImportError, e):

**Comment by GabsMarcelino** [comment]
Same here
